difftest/difftest-def.h
riscv/processor.h

Add a macro CONFIG_PMP_MAX_NUM to control the number of "implemented" PMP CSRs.
This is a implementation difference between XiangShan and SPIKE. 
* XiangShan only "implements" 16 PMP entries (CSRs), and it will trap when accessing 16\~63 PMP entries (CSRs), such as `pmpaddr16`. 
* SPIKE could be set to only have 16 PMP entries, but it "implements" all 64 of PMP entries (CSRs) and just set 16\~63 PMP entries read-only 0. It won't trap when accessing 16~63 PMP entries (CSRs), such as `pmpaddr16`. 
Both of them is accepted by RISC-V Spec.

difftest: fix unexcepted non-trap when accessing 16-63 PMP CSRs

---

difftest/difftest-def.h

Rewrite isa string define to allow enable RVV, RVH, or both.

config: rewrite isa string define to allow enable both RVV & RVH

---

difftest/difftest-def.h

Enable RVH difftest in spike as default, as XiangShan has merged H-ext implementation.

config: enable RVH for XiangShan as default

---

difftest/difftrace.h

NEMU could not enable dut_store_commit and performance optimization both, so to avoid memory leak, i think should close spike memory trace

store trace: could close store trace

---

riscv/execute.cc

This patch fixes OpenXiangShan/NEMU#353.
When difftesting, wfi should just be nop. Otherwise, wfi will stall without pc+1 and cause out of sync between dut and ref.

wfi: treat wfi as nop when difftest

---

difftest/difftest-def.h
difftest/difftest.cc
difftest/difftest.h
riscv/insn_template.h
riscv/insns/mret.h
riscv/processor.cc
riscv/processor.h
riscv/triggers.cc

Add difftest support for sdtrig CSR in spike except tcontrol and turn off sdtrig because tcontrol is not supported by spike.

Sdtrig: add difftest for sdtrig CSR in spike, and turn off it because it's not fully supported.

---

.github/workflows/build-difftest-so.yml

This patch add github action for building spike-so. This will simplify the procedure of bumping spike-so in NEMU ready-to-run.
Now you can find and download the spike-so in Action Summary page.

ci: add an ci to build spike-so automatically

---

difftest/difftest-def.h
riscv/mmu.h
riscv/processor.cc

XiangShan and NEMU are adding Sv48 support, so spike-so should also enable Sv48 for difftest. This patch move if-else-defined to difftest-def.h to make it clearer.
It seems we need something like menuconfig to arrange our configs. Now our difftest-def.h is so complex.

config: add config for paddr_bits and mmu_capability

---

riscv/trap.h

Currently, XiangShan and NEMU have support capturing the faulting instruction when illegal-instruction or virtual-instruction exception occurs. This patch allows the spike to do so when difftesting with XiangShan.

feat(trap): *tval captures inst on II & VI in XiangShan

---

difftest/difftest-def.h

This PR is a part of aligning NEMU's defconfigs.
Currently, the following extensions, although supported by XiangShan and NEMU, are still unusable during difftest with NEMU:
* AIA
* Sstc
* SMSTATEEN

config(XIANGSHAN): add sscofpmf, zfa & zfhmin

---

riscv/processor.cc

Currently, XiangShan only support writing 0 to htinst & mtinst CSRs when trap occurs. To align with XiangShan, this patch wraps the update of htinst & mtinst CSRs in take_trap function.

fix(csr): htinst/mtinst are always written 0 when trap in XiangShan

---

riscv/csr_init.cc

The modification is based on the following facts:
* Both XiangShan and NEMU support Zicntr extension, which includes three CSRs: cycle, time, instret.
* Rocket-chip support Zicntr except CSR time. In other words, Rocket-chip supports cycle and instret but does not support time.
* Nutshell does not support Zicntr.

feat(csr): modify the warp for CSR time

---

difftest/difftest-def.h
difftest/difftest.cc

Currently,
* Nutshell Rocket-chip does not support misaligned memory access
* XiangShan supports misaligned memory access for normal load/store, but does not support vector misaligned memory access.
Spike only supports enabling or disabling misaligned access for all memory access uniformly. This patch enables misaligned memory access of Spike for XiangShan, though it remains limited and not fully aligned between XiangShan and Spike.

config: add config for misaligned memory access

---

riscv/csr_init.cc

This is introduced by the last upstream merging.

fix(csr): duplicate add_csr for marchid and mimpid

---

riscv/csr_init.cc

When creating virtualized_csr_t for CSR sscratch, vsscratch has not been created yet. As a result, a NULL pointer is passed to virtualized_csr_t and Segment Fault occurs when accessing CSR sscratch when V=1.

fix: segment fault when access CSR sscratch when V=1

---

riscv/processor.cc

This patch reverts OpenXiangShan/riscv-isa-sim#33. According to RISC-V priv spec, htinst/mtinst could be zero when traps into HS/M-mode, except the both following conditions are met:
* the fault is caused by an implicit memory access for VS-stage address translation
* a nonzero value (the faulting guest physical address) is written to mtval2 or htval
Actually, XiangShan would write a nonzero value in such trap, so mtinst could not be written 0.
Acctually, spike only implements this nonzero situation for htinst/mtinst, so no more warps are needed.

revert(csr): htinst/mtinst should follow the origin spike behaviour

---

riscv/v_ext_macros.h

reduce VL and donot raise BP exception if trigger fired on a later element.

fix(vleff): reduce VL and donot raise BP exception on later element.

---

difftest/Makefile

Increase the maximum depth for finding .h files to 3, so that after modifying files in `riscv-isa-sim/riscv/insns/`, remake will not result in: `riscv64-spike-so is up to date`.

fix(Makefile): Increase maxdepth for finding .h files.

---

riscv/triggers.cc

The values of `count_read_value` and `pending_read_value` read by `stash_read_values` are not used in the middle function calls, including `detect_icount_fire`, `detect_icount_decrement`.
When spike runs as the DUT, both methods are acceptable.
When spike runs as the REF, I may need to read the value of `icount` after the current instruction executed, and before executing the next instruction.
In this case, the second method can achieve this because it calls `stash_read_values()` after `detect_icount_fire()` and `detect_icount_decrement()`, which may write the `count` and `pending` field in `icount`. And `tdata1_read()` for `icount` use the `count_read_value` and `pending_read_value`, rathen than `count` and `pending`.

fix(icount): place the read before the return of the caller.

---

riscv/mmu.h

If the sc instruction's addr is misaligned, it will check the addr trigger within the function check_load_reservation(), and raise misalign fault or access fault if addr trigger does not match.
However, for a properly aligned but failed sc instruction, spike does not execute the store function at all and does not check the addr trigger.
This patch checks the addr trigger right at the start of the sc instruction even if the sc instruction fails.

fix(sc): mcontrol6 addr trigger still match and fire for failed sc.

---

difftest/difftest.cc
difftest/difftest.h

This PR is used to pass XiangShan's Nightly CI test. 
`mtime` and `mtimecmp` are mmio type registers. We can change the values ​​of `mtime` and `mtimecmp` by writing data to memory. When `mtime` > `mtimecmp` will set `mip.mtip`.
When Spike running without using a dtb, skip the fdt-based configuration steps. There is no Clint in Spike's device tree. 
In order to allow Xiangshan and Spike to diff `mip` register, I update the mip.mtip bit through the difftest framework.

fix(mip): update mip.mtip when mtime > mtimecmp in CPU_XIANGSHAN 

---

riscv/mmu.cc

When spike processes a cross-page store, it will be split into two stores and the two stores are independent of each other.
This means that if the store on the lower page can be completed and the store on the upper page triggers a PF exception, the store on the lower page will still be written to memory, and a PF exception will be triggered using the store on the upper page.
For XiangShan, this store instruction can only be completed normally if both stores of the cross-page store can be completed normally.
This modification aligns Spike with XiangShan in the case of CPU = XiangShan.

fix(store): make cross-page access consistent with XiangShan behavior

---

difftest/difftest.cc
difftest/difftest.h

When we skip the difftest in the checkpoint restore phase, the pmp and pmp cfg registers will not be set to the correct values, this patch add two api to fix this problem

feat: add two api to support cpy pmp regs and pmp cfg regs

---

difftest/difftest.cc
riscv/cfg.h
riscv/vector_unit.cc

* If we first set the value of vtype using a register copy and the following vset instruction has the same value as that register, then non-register states such as vlmax will not be updated, and these states may have different values ​​than the register.

feat: support force flush non-reg values to avoid situations where non-register states are not set correctly in difftest

---

difftest/difftest.cc

The initial API accepts a string for the flash image file. To maintain compatibility with prior versions, we restore it.
We also rename the new API to v2.
This fixes the incompatibility introduced in #75

difftest: restore difftest_load_flash and add v2

---

difftest/difftrace.h

The unlikely macro is not included in some GCC versions.

fix(difftrace): use [[unlikely]] from C++20

---

difftest/Makefile

Previously, we only include `diffteset-def.h` in difftest-related files, which causes various inconsistencies in class or struct definitions.
Take `processor.h` for an example. The structure or size of `struct state_t` is dependent on the macro definition of `CONFIG_PMP_MAX_NUM` in `diffteset-def.h`. Different `CONFIG_PMP_MAX_NUM` results in different `struct state_t`, and further results in different `class processor_t`.
Considering that we includes `processor.h` and uses `class processor_t` in both `difftest/difftest.cc` and `riscv/sim.cc`, where the first `difftest/difftest.cc` has `CONFIG_PMP_MAX_NUM` defined but the second `riscv/sim.cc` not. If a variable of `class processor_t` is defined in one file and is used in another one (by global variable, return value of function call, …

fix(difftest): include `difftest-def.h` in spike

---

difftest/difftest.cc

For external and timer interrupts from outside, we choose to let the DUT inform the REF when there is a pending interrupt and trigger it.
For these types of interrupts, we set the corresponding bit in `mip` to 1 so Spike can trigger the interrupt itself. 
Moreover, we cannot modify these bits in `mip` using the `csrrw` instruction because the corresponding bit of `mip` is non-writable.
Therefore, after triggering the interrupt, we should also clear the corresponding bit in `mip`; otherwise, it will persist in `mip` indefinitely.

fix(raise_intr): fix raise_intr to allow clearing values in mip.

---

riscv/processor.cc

Multiple simultaneous interrupts destined for HS-mode are handled in the following decreasing priority order: SEI, SSI, STI, SGEI, VSEI, VSSI, VSTI, LCOFI.

fix(intr): fix the interrupt priority of LCOFI

---

riscv/csrs.cc

For implementations that support Smcdeleg/Ssccfg, Sscofpmf, Smaia/Ssaia, and the H extension, the LCOFI bit (bit 13) in each of hvip and hvien is implemented and writable. It means only when all of these extensions implemented, the LCOFI bit (bit 13) in each of hvip and hvien is writablt.

fix(hvip): Fix WMASK of LCOFI bit(bit 13) in hvip

---

riscv/csrs.cc
riscv/csrs.h

When the H extension is enabled, the mask of `vsatp.ppn` should be controlled by `hgatp`, while the mask of `satp.ppn` should not be affected.

fix(satp): fix mask of satp.ppn when write to satp and H ext enable

---

riscv/triggers.cc

CPU XiangShan only support trigger for address, which means that select bit in mcontrol/mcontrol6 is read-only zero.

fix(tdata1): fix the select bit in mcontrol/mcontrol6
